### ISSUE TITLE
No output on connecting and bill accepting

### ISSUE THREAD

**Issue by jaydattc** [RichAyotte/bill-validator#6]
I tried running one of the sample,
https://github.com/RichAyotte/bill-validator/blob/master/samples/apex-7000.js
and didn't got any output. I've cross checked usb address.
It seems it gets stuck on this if condition, I did got "message" as buffer on logging it.
> [bill-validator/lib/create-apex-7000.js](https://github.com/RichAyotte/bill-validator/blob/ae200eb50d01cd0f4730e9d5d77c0f8362e4b3ec/lib/create-apex-7000.js#L100)

```javascript
		, async start() {
			ioInterface.on('data', message => {
				const receivedAck = apex7000Spec.getMessageAck(message)
				if (stateManager.ack === receivedAck) {
					stateManager.flipAck()
					stateManager.updateState({message})
					Object.entries(stateManager.stateChanges).forEach(([prop, value]) => {
						apex7000.emit(prop, value)
					})
				}
			})
			await ioInterface.open()
			await reset()
		}
```

**Comment by RichAyotte** [comment]
Can you share a repro?

**Comment by jaydattc** [comment]
did you meant issue reproduction?

**Comment by RichAyotte** [comment]
If no changes were made to the sample please provide the following.
- The command and its output including any errors or exceptions
- Operating system
- Node.js version

**Comment by RichAyotte** [comment]
Closing. No response from submitter.
